### PR TITLE
Feature: Key and Index Accessors Inside Loops

### PR DESCRIPTION
**Pull request by Swivelgames**
Implements #56

### CODE REVIEW

**Comment by Swivelgames** [comment]
<details>
<summary>Passes on all BASH versions with ./run-tests using fidian/multishell-small</summary>

```
root@11b0b34821e1:/var/mo# run-script-againt-shells bash ./run-tests-quietly
bash-2.05.0: pass
bash-3.1.23: pass
bash-3.2.57: pass
bash-4.0.44: pass
bash-4.1.17: pass
bash-4.2.53: pass
bash-4.3.48: pass
bash-4.4.23: pass
bash-5.0.18: pass
bash-5.1.8: pass
```

</details>

**Comment by fidian** [comment]
Sorry for not making this more clear earlier when I asked you to combine the logic. Could you make two changes?

1. The example in `README.md` uses `@`. No label. Would you change this to `@key`?
2. Would you remove `@index` or change it's implementation? If we were to follow Handlebars, then `@index` would be a 0-based numeric value when iterating across objects. That might be more work to properly support and I would rather get `@key` implemented because you've expressed a need for this functionality.

**Comment by Swivelgames** [comment]
@fidian Ah! My apologies. I had originally implemented `@index` to only output if it was a 0-based number, but I don't have an immediate need for it, so we can certainly reimplement this if someone ever has a major need for it.

As for the README, I must have totally overlooked that. Good catch :sweat_smile:

**Comment by Swivelgames** [comment]
Done!

**Comment by fidian** [comment]
Excellent, thanks!

**Pull request merged**
