### PR TITLE
Added dockerfile and release GitHub Action

### PR DESCRIPTION
**Pull request by yutachaos**
# Description
- Added image build and push CI to GitHub Container Registry for use in containers

## FYI
- https://docs.github.com/en/packages/guides/about-github-container-registry

### CODE REVIEW

**Comment by fidian** [comment]
Is qemu used for the arm64 build? I'm curious because this is just written in shell code and I'm hoping you can tell me why I need a machine emulator.

**Comment by yutachaos** [comment]
> Is qemu used for the arm64 build? I'm curious because this is just written in shell code and I'm hoping you can tell me why I need a machine emulator.

I'm using your code in a container and want it to work on both arm cpu instances and amd cpu instances.

If you prepare images of both cpu with the function of Docker, you can automatically pull the image of the appropriate cpu, so both images are built.

- FYI
     - https://aws.amazon.com/ec2/graviton/
     - https://www.smartling.com/resources/product/building-multi-architecture-docker-images-on-arm-64-bit-aws-graviton2/

**Comment by fidian** [comment]
Looks good to me.

**Comment by fidian** [comment]
Thanks for supplying this pull request!

**Comment by yutachaos** [comment]
@fidian 
Thank you for merging.

The docker build will run when the tag is created, so I'd be happy if you could create a new tag if possible. 🙏 
https://github.com/tests-always-included/mo/pull/45/files#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR14

**Comment by sugarshin** [comment]
@fidian could you please create a git-tag?

> The docker build will run when the tag is created,

**Comment by fidian** [comment]
Sorry for the huge delay. I've just created the tag 2.3.0.

**Pull request merged**
