### PR TITLE
Added github actions CI

### PR DESCRIPTION
**Pull request by yutachaos**
# Description 
- Add CI using github actions

### CODE REVIEW

**Comment by fidian** [comment]
This uses Go? There's a comment indicating it does. Can you tell me more about it?

**Comment by yutachaos** [comment]
> This uses Go? There's a comment indicating it does. Can you tell me more about it?

Sorry.
I just forgot to modify the code that I copied and pasted, and I don't use Go.
Fixed.

**Comment by fidian** [comment]
I hesitate to include a `package-lock.json` file in this repository because it is not a Node.JS project. I only use those packages for testing. When there is a `package-lock.json` file, dependabot will scan the repo and look for vulnerabilities and audit the packages, then I will get far more pull requests on something that isn't strictly necessary.

I am unsure, but it might be a good idea for me to switch from `package.json` for testing and instead use a container or some shell code to run a script like what I have below. What do you think? **Note:** I am not asking you to do more work. I would do the following right after merging your code in order to eliminate `package-lock.json`.

    #!/usr/bin/env bash
    # Create a package.json so the dependency package is installed in the local directory
    echo '{"private":true, "dependencies":{"async": "*"}}' > package.json
    npm install
    if [[ ! -d spec ]]; then
        git clone https://github.com/mustache/spec.git spec
    else
        (
            cd spec;
            git pull
        )
    fi
    node run-spec.js spec/specs/*.json

**Comment by yutachaos** [comment]
I see.
Deleted package-lock.json.

**Comment by fidian** [comment]
I merged your code but changed the commands to run the two in the repository. Thank you very much for your contribution and I am sorry it took me so long to get to this.

**Pull request merged**
